batchsize: 60
hidden_size: 128
learning_rate: 0.0004618836422556036
lin_layer_dim: 48
lin_layer_num: 0
lstm_layer_num: 1
num_layers: 2
weight_decay: 1.214174649108876e-05
weight_initializer: kaiming
window_size: 24
