batchsize: 48
hidden_size: 128
learning_rate: 0.0005393725808043456
lin_layer_dim: 32
lin_layer_num: 2
lstm_layer_num: 2
num_layers: 2
weight_decay: 1.0300376241062739e-05
weight_initializer: xavier
window_size: 48
